str = "i am a code"
endStr = str.endswith('code')
print(endStr)
cap = str.capitalize()
print(cap)
rep = str.replace("code" , "Engineer")
print(rep)
find = str.find("o")
print(find)
coun = str.count("a")
print(coun)